### ISSUE TITLE
Branch dev_multiagent AssertionError

### ISSUE THREAD

**Issue by LAS1520** [rte-france/Grid2Op#414] opened 2023-02-22 16:21 UTC
Hi! I'm having some problems and I'd like your help.
## Bug description
In the branch dev_multiagent, when I used the environment "l2rpn_neurips_2020_track2_small", I got an AssertionError.

### Code snippet

```python
import grid2op
from grid2op.multi_agent import MultiAgentEnv
env_name = "l2rpn_neurips_2020_track2_small"
cent_env = grid2op.make(env_name)
# agent_name : controlled substation id
zones = {
    'agent_0': [40, 39, 41, 52, 53,
                32, 38, 54, 58,
                36, 43, 51, 55,
                33, 42, 57, 56, 62,
                44, 50, 49,
                34, 35, 45, 47, 59,
                37, 46, 48, 61, 60,
                71, 70, 72, 65, 66, 63,
                23, 69, 68, 67, 64, 115],
    'agent_1': [73, 78, 80,
                74, 117, 77,
                75, 79, 98,
                76, 96, 97, 105,
                81, 95,
                82, 94, 93, 99, 103, 104, 106,
                83, 84, 87, 88, 91, 92, 107,
                101, 100, 102, 108,
                85, 86, 89, 90, 110, 109, 111],
    'agent_2': [0, 1, 116, 2, 11, 13,
                3, 10, 4, 5, 6, 12, 14,
                15, 18, 112, 16, 17, 19,
                7, 29, 8, 28, 30, 20,
                9, 27, 31, 21, 26, 113,
                114, 25, 22, 24]
}
env = MultiAgentEnv(cent_env, action_domains=zones)
... # Some code 
```

## Current output

```
    assert self._cent_env.parameters.MAX_LINE_STATUS_CHANGED == self.num_agents
AssertionError
```
I printed "self._cent_env.parameters.MAX_LINE_STATUS_CHANGED" and "self.num_agents" and in this case, "self._cent_env.parameters.MAX_LINE_STATUS_CHANGED"=1 and “self.num_agents=3”, that's why the AssertionError appeared. However, when I used the environment "l2rpn_case14_sandbox", it worked correctly without any error.

**Comment by BDonnot** [comment] 2023-03-08 09:52
Hello,

You can change the number of `MAX_LINE_STATUS_CHANGED` (and `MAX_SUB_CHANGED`) in the parameters of the env:


```python
import grid2op
from grid2op.multi_agent import MultiAgentEnv
env_name = "l2rpn_neurips_2020_track2_small"
cent_env = grid2op.make(env_name)

param = cent_env.parameters
param.MAX_LINE_STATUS_CHANGED = 3
param.MAX_SUB_CHANGED = 3
env.change_parameters(param)
env.change_forecast_parameters(param)
env.reset()  # otherwise it's not taken into account


# rest of your code
```

**Comment by BDonnot** [comment] 2023-03-08 09:53
This behaviour is a feature and not a bug. It tells you explicitly that if you try to apply multi agent in a setting where only one "agent" could be able to act is not a great idea at all.

**Comment by LAS1520** [comment] 2023-03-08 12:04
Thanks for reply! But I don't understand the meaning of "in a setting where only one "agent" could be able to act". What's the difference betweent this environment "l2rpn_neurips_2020_track2_small" and other environments like "l2rpn_neurips_2020_track1_small" without that behaviour? The words "one "agent"" in your sentence confuses me.

**Comment by BDonnot** [comment] 2023-03-08 14:06
From the doc: 
> MAX_SUB_CHANGED: ``int`` Maximum number of substations that can be reconfigured between two consecutive timesteps by an  :class:`grid2op.Agent.BaseAgent`. Default value is 1.

> MAX_LINE_STATUS_CHANGED: ``int`` Maximum number of powerlines statuses that can be changed between two consecutive timesteps by an  :class:`grid2op.Agent.BaseAgent`. Default value is 1.

So basically if you have 3 agents, but you only for 1 substation to be modified at a given time in the original centralized env (*ie* `cent_env.parameters.MAX_SUB_CHANGED = 1`) then when you combine the 3 "local action" of each "agents" it might (and will, in most cases) modify 3 substations at the same time (1 per agent) and the "centralized action" combined will then be illegal (because it modifies 3 substations and not 1)

**Comment by LAS1520** [comment] 2023-03-08 14:29
I get it. Thank you very much!

**Comment by BDonnot** [comment] 2023-06-06 12:19
I'm closing this issue as the problem appears to have been fixed. Feel free to re open it if needed.

**Closed by BDonnot** 2023-06-06 12:19 UTC
Labels: question
