### ISSUE TITLE
Score/Timestep on l2rpn_neurips_2020_track1_small for DoNothingAgent changes on each execution

### ISSUE THREAD

**Issue by AvisP** [rte-france/Grid2Op#432] opened 2023-03-28 14:49 UTC
## Environment
 - Grid2op version: `1.8.1`
 - System: `osx`

## Bug description
When a DoNothing agent is executed using Runner class and evaluated on l2rpn_neurips_2020_track1_small environment, then the scores and time steps are different for different execution. The same doesn't happen for l2rpn_case14_sandbox.

## How to reproduce
The issue can be reproduced by running the following code snippet

```
import grid2op
from grid2op.Runner import Runner
from grid2op.Reward import LinesCapacityReward 
from lightsim2grid import LightSimBackend 

nb_episode = 5
nb_process = 1

env_name = "l2rpn_neurips_2020_track1_small"
env = grid2op.make(env_name,
                    reward_class=LinesCapacityReward,
                    backend=LightSimBackend()
                    )

runner_params = env.get_params_for_runner()
runner = Runner(**runner_params)

res = runner.run(nb_episode=nb_episode,
                nb_process=nb_process
                )

print("Evaluation summary for DN:")
for _, chron_name, cum_reward, nb_time_step, max_ts in res:
    msg_tmp = "chronics at: {}".format(chron_name)
    msg_tmp += "\ttotal score: {:.6f}".format(cum_reward)
    msg_tmp += "\ttime steps: {:.0f}/{:.0f}".format(nb_time_step, max_ts)
    print(msg_tmp)
```

Execute it once, make a note of the timestep and scores and then execute the **whole** code section not just the for loop and the scores, timesteps will be different.

Kindly suggest ways to resolve it. Thanks!

**Comment by BDonnot** [comment] 2023-03-29 09:17
Please, before submitting a bug, try to read the documentation... Because clearly in this case it's not a bug but a misunderstanding from your side of what is a "non deterministic environment" 

In order to have reproducible results you need to **SEED** the environment (when it's not deterministic) 

Look at the doc here https://grid2op.readthedocs.io/en/latest/runner.html#grid2op.Runner.Runner.run and you know how to set the seeds with the runner. 

I'm closing the "issue"

**Closed** 2023-03-29 09:17 UTC
Labels: bug

**Comment by AvisP** [comment] 2023-03-29 14:31
Hi Benjamin,

Thanks for your prompt reply, resolving it quickly and sorry about posting the issue. The label "bug" gets assigned automatically when I post an issue, I will make sure to tag it as "question" on similar queries in future.
