### ISSUE TITLE
Not working line reconnection rule properly

### ISSUE THREAD

**Issue by sunghoonhong** [rte-france/Grid2Op#59] opened 2020-04-20 15:37 UTC
Hello, I've got a new issue.

From the documentation, 
```BaseObservation.time_before_line_reconnectable```
(number of timestep to wait before a powerline can be reconnected (it is disconnected due to maintenance, cascading failure or overflow))

I observed that ```time_before_line_reconnectable```is properly given in my ```obs```, after the powerline was disconnected by overflow.
However, it seems that the disabling reconnection of the powerline (by the default rule) does not work.
That is, when I try to reconnect the powerline before the ```time_before_line_reconnectable``` is done, it still work.
Even in the information from env.step(), there is not any exception or illegalAction.

I would like to inform you this issue!

Best Regards

**Comment by BDonnot** [comment] 2020-04-20 18:19
Hello Sunghoon,

Thanks a lot for letting us know.
We will release a new version soon, a fix for this issue will be made in version 0.7.1. We will also make sure to include some testing for this feature. For now, the cooldown has been tested for the substation, but apparently we didn't cover the case of the powerlines.
We'll for sure improve the situation. 
Thanks

Benjamin

**Comment by BDonnot** [comment] 2020-04-22 18:26
Hello, the fix for this issue has been released in version 0.7.1 that has been pushed today.
I'm closing the issue. Don't hesitate to re open it if the the problem is not solve.

Thanks again

Benjamin

**Closed by BDonnot** 2020-04-22 18:26 UTC
Labels: bug
