### ISSUE TITLE
Error when creating a new environment with LightSimBackend

### ISSUE THREAD

**Issue by AvisP** [rte-france/Grid2Op#393] opened 2023-01-09 17:10 UTC
## Environment
 - Grid2op version: `1.8.0`
 - System: `macos 12.6.2 `
 - Python: `3.10.7`

## Bug description
When trying to create a gym environment and using LightSimGrid as backend, there is an error produced but when using Pandapower as backend there is no error.

## How to reproduce
Running the following set of code will produce the error
```
import os
import sys
from lightsim2grid.lightSimBackend import LightSimBackend
from grid2op.gym_compat import GymEnv
import grid2op
from gym import Env
from gym.utils.env_checker import check_env
try:
#     from lightsim2grid import LightSimBackend
    bk_cls = LightSimBackend
except ImportError as exc:
    print(f"Error: {exc} when importing faster LightSimBackend")
# from grid2op.Backend import PandaPowerBackend
# bk_cls_panda = PandaPowerBackend
    
env_name = "l2rpn_case14_sandbox"
training_env = grid2op.make(env_name, backend=bk_cls())  # we put "test=True" in this notebook because...
# it's a notebook to explain things. Of course, do not put "test=True" if you really want
# to train an agent...
gym_env = GymEnv(training_env)
```

The error message generated is
```
Traceback (most recent call last):
  File "/Users/paula/Desktop/Projects/RL Practice/L2RPN Aspen/Demo Notebooks/LightSimBackend_test.py", line 22, in <module>
    training_env = grid2op.make(env_name, backend=bk_cls())  # we put "test=True" in this notebook because...
  File "/Users/paula/Desktop/Projects/venvs/L2PRN_G2O_1_8_0/lib/python3.10/site-packages/grid2op/MakeEnv/Make.py", line 427, in make
    return make_from_path_fn(
  File "/............./L2PRN_G2O_1_8_0/lib/python3.10/site-packages/grid2op/MakeEnv/MakeFromPath.py", line 764, in make_from_dataset_path
    env = Environment(
  File "/............./venvs/L2PRN_G2O_1_8_0/lib/python3.10/site-packages/grid2op/Environment/Environment.py", line 161, in __init__
    self._init_backend(
  File "/............../venvs/L2PRN_G2O_1_8_0/lib/python3.10/site-packages/grid2op/Environment/Environment.py", line 396, in _init_backend
    *_, fail_to_start, info = self.step(do_nothing)
  File "/............../venvs/L2PRN_G2O_1_8_0/lib/python3.10/site-packages/grid2op/Environment/BaseEnv.py", line 2806, in step
    init_line_status = copy.deepcopy(self.backend.get_line_status())
  File "/............../venvs/L2PRN_G2O_1_8_0/lib/python3.10/site-packages/lightsim2grid/lightSimBackend.py", line 898, in get_line_status
    l_s = self._grid.get_lines_status()
AttributeError: 'NoneType' object has no attribute 'get_lines_status'
Exception ignored in: <function BaseEnv.__del__ at 0x13c82beb0>
Traceback (most recent call last):
  File "/.............../venvs/L2PRN_G2O_1_8_0/lib/python3.10/site-packages/grid2op/Environment/BaseEnv.py", line 3576, in __del__
    self.close()
  File "/.............../venvs/L2PRN_G2O_1_8_0/lib/python3.10/site-packages/grid2op/Environment/BaseEnv.py", line 3070, in close
    self.backend.close()
  File "/.............../venvs/L2PRN_G2O_1_8_0/lib/python3.10/site-packages/lightsim2grid/lightSimBackend.py", line 584, in close
    self.init_pp_backend.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

However when running with backend as Pandapower this issue does not occur.

**Comment by BDonnot** [comment] 2023-01-09 17:19
Hello,

Thanks for raising the issue.

It appears to be a lightsim2grid isuue that I'll address there.

Sorry for the inconvenience.

**Comment by AvisP** [comment] 2023-01-09 17:55
Hi Benjamin,

Thanks for your prompt response. No issues! Should I create an issue on lightsim2grid git repo?

**Comment by BDonnot** [comment] 2023-01-09 18:05
If you can then yes you can close this one and ope' another one there.

Otherwise I'll just reference this one in lightsim2grid when I'll fix it. And it will be closed only when a new version of lightsim2grid is released (this was a note to myself more than anything)

**Comment by BDonnot** [comment] 2023-01-10 08:37
Hello,

The real fix will be pushed "at some point" (when a release of lightsim will be made), but before I do there are different things i need to do. So this will have to wait a bit, unfortunately (lightsim is next on my todo list however).

This is due to some incompatibility with recent numpy version and some types used by grid2op / lightsim2grid. Maybe first you can try to **DOWNGRADE NUMPY TO VERSION 1.23** or bellow and see if it works.

**IF** it does not work, as a "quick and dirty" fix there are different thing you need to do for it to work:
1) change the file /.............../venvs/L2PRN_G2O_1_8_0/lib/python3.10/site-packages/grid2op/dtypes.py to have (last line) `dt_bool = bool` instead of `dt_bool = np.bool`
2) change the file /.............../venvs/L2PRN_G2O_1_8_0/lib/python3.10/site-packages/lightsim2grid/securityAnalysis.py to have:
```python
    try:
        STR_TYPES = (str, np.str, np.str_)
    except:
        # most recent numpy version
        STR_TYPS = (str, np.str_)
``` 
instead of simply `STR_TYPES = (str, np.str, np.str_)`

And then you will most likely need to change the `/............../venvs/L2PRN_G2O_1_8_0/lib/python3.10/site-packages/lightsim2grid/lightSimBackend.py` file and replace it with the one attached:
[lightSimBackend.zip](https://github.com/rte-france/Grid2Op/files/10380605/lightSimBackend.zip)

You will need to do that each time you install / update lightsim2grid or grid2op (until of course I fixed the issue)

Let me know if this solves your problem. Hopefully it does :-)

Benjamin

**Comment by AvisP** [comment] 2023-01-10 13:55
Hi Benjamin, 

Thanks for providing the quick fix! Much appreciated! I ran into a new issue while testing with the lightSimBackedn.py that you sent. Here is the error message. Can you have a look into it when you can? 

```
NoneType' object has no attribute 'get_lines_status'
  File "/.............../venvs/L2PRN_G2O_1_8_0/lib/python3.10/site-packages/lightsim2grid/lightSimBackend.py", line 898, in get_line_status
    l_s = self._grid.get_lines_status
  File "/.............../venvs/L2PRN_G2O_1_8_0/lib/python3.10/site-packages/grid2op/Environment/BaseEnv.py", line 2806, in step
    init_line_status = copy.deepcopy(self.backend.get_line_status())
  File "/.............../venvs/L2PRN_G2O_1_8_0/lib/python3.10/site-packages/grid2op/Environment/Environment.py", line 396, in _init_backend
    *_, fail_to_start, info = self.step(do_nothing)
  File "/.............../venvs/L2PRN_G2O_1_8_0/lib/python3.10/site-packages/grid2op/Environment/Environment.py", line 161, in __init__
    self._init_backend(
  File "/.............../venvs/L2PRN_G2O_1_8_0/lib/python3.10/site-packages/grid2op/MakeEnv/MakeFromPath.py", line 764, in make_from_dataset_path
    env = Environment(
  File "/.............../venvs/L2PRN_G2O_1_8_0/lib/python3.10/site-packages/grid2op/MakeEnv/Make.py", line 427, in make
    return make_from_path_fn(
  File "/............../RL Practice/L2RPN Aspen/Demo Notebooks/LightSimBackend_test.py", line 22, in <module>
    training_env = grid2op.make(env_name, backend=bk_cls())  # we put "test=True" in this notebook because...
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main (Current frame)
    return _run_code(code, main_globals, None,
```

**Comment by BDonnot** [comment] 2023-01-10 14:02
Is this the whole error message ? It's the first time I see an erreor caused by "_run_code" so this must be a really tricky one...

The provided fix works on my machine, so I assume it's an issue with macos / python on macos :-/

**Comment by AvisP** [comment] 2023-01-10 14:20
Apologies for making it complicated, I was in debug mode which is why you saw those "_run_code" messages. when it hit line 898 in lightSimBackend.py I saw that self._grid is NoneType which is the source of error. Please find the updated error message below 

```
/Users/paula/Desktop/Projects/venvs/L2PRN_G2O_1_8_0/lib/python3.10/site-packages/pandapower/auxiliary.py:272: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item, dtype in list(dtypes.iteritems()):
Traceback (most recent call last):
  File "/.............................../Demo Notebooks/LightSimBackend_test.py", line 22, in <module>
    training_env = grid2op.make(env_name, backend=bk_cls())  # we put "test=True" in this notebook because...
  File "/............................/venvs/L2PRN_G2O_1_8_0/lib/python3.10/site-packages/grid2op/MakeEnv/Make.py", line 427, in make
    return make_from_path_fn(
  File "/............................./venvs/L2PRN_G2O_1_8_0/lib/python3.10/site-packages/grid2op/MakeEnv/MakeFromPath.py", line 764, in make_from_dataset_path
    env = Environment(
  File "/............................/venvs/L2PRN_G2O_1_8_0/lib/python3.10/site-packages/grid2op/Environment/Environment.py", line 161, in __init__
    self._init_backend(
  File "/............................/venvs/L2PRN_G2O_1_8_0/lib/python3.10/site-packages/grid2op/Environment/Environment.py", line 396, in _init_backend
    *_, fail_to_start, info = self.step(do_nothing)
  File "/............................/venvs/L2PRN_G2O_1_8_0/lib/python3.10/site-packages/grid2op/Environment/BaseEnv.py", line 2806, in step
    init_line_status = copy.deepcopy(self.backend.get_line_status())
  File "/............................/venvs/L2PRN_G2O_1_8_0/lib/python3.10/site-packages/lightsim2grid/lightSimBackend.py", line 898, in get_line_status
    l_s = self._grid.get_lines_status
AttributeError: 'NoneType' object has no attribute 'get_lines_status'
Exception ignored in: <function BaseEnv.__del__ at 0x12ef2beb0>
Traceback (most recent call last):
  File "/............................/venvs/L2PRN_G2O_1_8_0/lib/python3.10/site-packages/grid2op/Environment/BaseEnv.py", line 3576, in __del__
    self.close()
  File "/............................/venvs/L2PRN_G2O_1_8_0/lib/python3.10/site-packages/grid2op/Environment/BaseEnv.py", line 3070, in close
    self.backend.close()
  File "/............................/venvs/L2PRN_G2O_1_8_0/lib/python3.10/site-packages/lightsim2grid/lightSimBackend.py", line 584, in close
    self.init_pp_backend.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

**Comment by BDonnot** [comment] 2023-01-10 14:36
Thanks for the precision. I did not understood you were in debug mode.

Have you updated lightsim2grid with the most recent version ? Because i honestly don't know why self._grid would be None as it is initialized above, precisely in `self.backend.load_grid(...)` line 228 of this Environment.py. And if you go in lightSimBackend.py, line 300 (definition of the `load_grid` function, you will notice that `self._grid = init(self.init_pp_backend._grid)` so it is set to something there.

Can you add `assert self._grid is not None` at line 301 (just after the above call to `init`) to check if the problem is there ?

(sorry for the asking you to do this, but as I cannot reproduce your error I have no way to do it :-( )

**Comment by AvisP** [comment] 2023-01-10 15:39
Hi Benjamin, Looks like I did something silly. I copied the python file you gave to wrong environment which caused all these things I mentioned. Sorry about that. It is working properly without any issues now. Thanks!

**Comment by BDonnot** [comment] 2023-01-10 16:08
Nice 😊

Glad I could help!

**Comment by BDonnot** [comment] 2023-01-11 14:42
Hello, 

I close the issue as this should work now: both lightsim2grid and grid2op have been updated to fix this issue.

I also added some tests (in lightims2grid repo) to make sure that you can install the package from pypi and create an environment with LightSimBackend. 

Let me know if you encounter any issues with it :-)

**Closed by BDonnot** 2023-01-11 14:42 UTC
Labels: bug
