### ISSUE TITLE
Reward function does not reflect gen cost values

### ISSUE THREAD

**Issue by jhmenke** [rte-france/Grid2Op#41] opened 2020-03-05 08:39 UTC
In the reward, the marginal cost is defined as the maximum costs of any active generator:

`marginal_cost = np.max(env.gen_cost_per_MW[env.gen_activeprod_t > 0.])`

However, the gen_cost_per_MW is not equal for all controllable generators:

`array([40., 70.,  0.,  0., 70.])`

For an economic optimum, using the generator with costs of 40 would be preferential. This is currently not reflected in the reward function. Is this intentional?

Since the generator with costs of 40 can likely not be used exclusively (while the 70 cost generators are shut down), the reward function would always have marginal costs of 70. 

I could set all costs to 70 and not have any disadvantages regarding the reward. Or does this have other unintended consequences?

An example: Maybe the system losses are minimized when only the cost 70 generators are used. However, due to the cost functions, it may be economically preferential to use the 40 cost generator too and thus the result of an OPF. This is not reflected in the reward.

**Comment by BDonnot** [comment] 2020-03-05 09:30
Hello Jan-Hendrik,

This feature is not a bug (for once :smiley: ). This is to reflect the TSO point of view.

A TSO, as far as I know, need to buy the losses on the electricity market. So they pay something depending on the marginal cost of the grid basically. This means that losses when demands is high (thus inducing high prices -- offer and demand) are more expensive (for real operation) than losses when prices are low.

In order to mimic this behavior in grid2op, we choose the marginal cost to be the cost the most expensive turned on generator. We might change this reward for the real competition.

**Comment by jhmenke** [comment] 2020-03-05 09:39
Would setting the cost of all generators to an equal value be a feasible workaround for now?

**Comment by BDonnot** [comment] 2020-03-05 09:50
In the short term, for the reward / score yes, definitely.

This would mean changing the environment, that is why i think recoding the reward function is a more flexible way, and closer to what will happen for this year competitions. The score will be fixed and determined by the organization (after some thoughts about it) but participants will be free to modify the reward as much as they want.

I plan on working on defining more easily custom scores / rewards and better explain it (see issue #11) soon.

**Comment by BDonnot** [comment] 2020-03-20 15:12
Hello,

I'm closing this issue and thanks for reaching out concerning this problem of definition of "marginal cost" of a powergrid.

We'll keep that in mind when we'll design the rules for L2RPN 2020 competition(s)

Benjamin

**Closed by BDonnot** 2020-03-20 15:12 UTC
