### ISSUE TITLE
Exception resulting from illegal action is not propagated in obs.simulate

### ISSUE THREAD

**Issue by jhmenke** [rte-france/Grid2Op#31] opened 2020-02-06 14:45 UTC
While running an environment the simulation stopped abruptly without any apparent errors.
Only after some tedious debugging it became clear that an action is illegal:

>  File "<ipython-input-6-ca29e0dfdf29>", line 1, in <module>
>     action()
>   File "/home/jmenke/Documents/PythonProjects/Grid2Op/grid2op/Action.py", line 1605, in __call__
>     self._check_for_ambiguity()
>   File "/home/jmenke/Documents/PythonProjects/Grid2Op/grid2op/Action.py", line 1136, in _check_for_ambiguity
>     " which bus.".format(q_id))
> grid2op.Exceptions.InvalidLineStatus: Grid2OpException AmbiguousAction InvalidLineStatus "You ask to reconnect powerline 5 yet didn't tell on which bus."

I would expect that this exception would be propagated and raised properly with the default settings.

**Comment by jhmenke** [comment] 2020-02-06 15:07
Furthermore, using "change_line_status" instead of "set_line_status" seems also to be causing some issues.

Status before the action is line0 is connected and line5 is disconnected. This action should therefore connect line5 while disconnecting line0:


> This action will:
> 	 - NOT change anything to the injections
> 	 - NOT perform any redispatching action
> 	 - NOT force any line status
> 	 - switch status of 2 powerlines ([0 5])
> 	 - NOT switch anything in the topology
> 	 - NOT force any particular bus configuration

However, in the pandapowerBackend call to apply_action, the result of this call

`dict_injection, change_status, switch_status, set_topo_vect, switcth_topo_vect, redispatching = action()`

leads to *change_status* being: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Consequently, nothing is actually changed in the grid.

**Comment by BDonnot** [comment] 2020-02-06 15:31
Can you please send me a piece of code that does just that ? I'm asking because I think the reason of why the action was not implemented has been returned in the "info" part of the `env.step` method.

There is however a problem for "obs.simulate" that should return these information but does not at the moment `obs.simulate` is a bit behind `env.step` and I will work on this in the next release.

**Comment by BDonnot** [comment] 2020-02-06 15:37
By design, i made the choice not to propagate the error because i think it's common in "video game". 

In pacman for example, when you face a wall and you ask to go ahead, the game don't crash, and nothing is done. This behaviour is pretty common in RL environment: at the beginning of the training of an agent, they will do this kind of "mistake" a lot. 

I agree this should be more explicit.

**Comment by jhmenke** [comment] 2020-02-06 15:46
>Can you please send me a piece of code that does just that ? I'm asking because I think the reason of why the action was not implemented has been returned in the "info" part of the env.step method.

Ah that may be it! I was looking at another flag returned by simulate, but it could have been the wrong one! I can send you the relevant code tomorrow if that's still an issue after you helpful comments.

>By design, i made the choice not to propagate the error because i think it's common in "video game".

Sure, it makes total sense for reinforcement learning, sorry! I have to get used to the different approach of not requiring any reasons for why something does not work and just using the reward as the signal.

It seems to be personal confusion for most of these issues and not actually bugs in you software :) Again, thanks for the quick support!

**Comment by BDonnot** [comment] 2020-02-06 16:18
I will be more explicit, and especially in the "obs.simulate" function that need to be reworked :-)

You can look in the "env.step" last returned value, which is called "info":
```python
observation, reward, done, info = env.step(action)
```

This should give you more information. However, in the current version, `obs.simulate` does not reflect all of this information.

Thanks again for the valuable feedback :-)

**Comment by BDonnot** [comment] 2020-03-03 15:54
Hello,

This should be fixed in the new 0.5.7 version that i just released today.

Benjamin

**Closed by BDonnot** 2020-03-03 15:54 UTC
Labels: enhancement
