### ISSUE TITLE
Nan in the state vector after converting using "to_vect()"

### ISSUE THREAD

**Issue by KishanGitASU** [rte-france/Grid2Op#14] opened 2019-12-10 00:50 UTC
State class object when converted to a vector form using "to_vect()", me and @amar-iastate observed sometimes "nan"s in the state vector. We are attaching the "state" when the power grid is good and the "action" taken to reach "next state". The next state has a "nan" in it. 

[state_action_nextState_info.zip](https://github.com/rte-france/Grid2Op/files/3942484/state_action_nextState_info.zip)

**Comment by amar-iastate** [comment] 2019-12-12 17:09
The "nan" was observed in the "v_or" and "v_ex" fields of the observation. Mostly this seems to be occurring on lines whose "ex"/"or"  terminal is on a bus with no other elements. To see this, run the following code
`from grid2op.MakeEnv import make`
`env = make()`
`env.reset()`
`action = env.helper_action_player({"change_bus": {"lines_or_id": [17]}})`
`obs, reward, done, info = env.step(action)`
`print(obs.v_or) # this will have 'nan' in the 17th element`

This seems to be caused by the backend code. After a bit of digging in the code, I observed that the value of `self._grid.res_trafo["vm_hv_pu"].values` from the pandapower output in the function `_aux_get_line_info` in the file `BackendPandaPower` has a 'nan'. So, the issue is in the pandapower code. Can @BDonnot and @FlorianShepherd check it out?

Thanks
Amar

**Comment by FlorianShepherd** [comment] 2019-12-13 10:55
What is the action? Is a switch opened or something set out of service?

If not the whole dataframe is filed with nans, but only some values, then the bus of the trafo could be disconnected. What's the value of that bus in res_bus?

**Comment by amar-iastate** [comment] 2019-12-13 15:45
As the code above shows, the action in this case is switching of the origin of line 17 to busbar 2. Nothing is set out of service. 
I have not used pandapower till now and I am not sure what you mean by "bus of the trafo could be disconnected". As I am only switching the busbar, there should be no disconnection. The value of `self._grid.res_bus` is shown below. I am not able to understand why there are 24 entries for a 14 bus system.
`       vm_pu  va_degree        p_mw     q_mvar`
`0   1.060000   0.000000 -150.898912   0.883423`
`1   1.045000  -3.419421   18.800000 -34.083132`
`10  1.047736  -5.654338    3.200000   2.200000`
`11  1.049713  -4.571854    5.600000   4.000000`
`12  1.043076  -4.878533   11.900000   8.300000`
`13  1.015820  -7.317196   13.600000   9.500000`
`2   1.010000  -7.965181   63.000000   1.139708`
`3   1.010738  -5.821196   44.500000  31.200000`
`4   1.019972  -4.562126    7.100000   4.900000`
`5   1.070000  -3.699960  -59.200000  -7.180676`
`6   1.052113  -7.173603    0.000000   0.000000`
`7   1.090000  -7.173603    0.000000 -23.444401`
`8   1.038486  -7.881571   27.600000  -1.790629`
`9   1.035703  -7.384004    8.100000   5.700000`
`14       NaN        NaN    0.000000   0.000000`
`15       NaN        NaN    0.000000   0.000000`
`24       NaN        NaN    0.000000   0.000000`
`25       NaN        NaN    0.000000   0.000000`
`26       NaN        NaN    0.000000   0.000000`
`27       NaN        NaN    0.000000   0.000000`
`16       NaN        NaN    0.000000   0.000000`
`17       NaN        NaN    0.000000   0.000000`
`18       NaN        NaN    0.000000   0.000000`
`19       NaN        NaN    0.000000   0.000000`
`20       NaN        NaN    0.000000   0.000000`
`21       NaN        NaN    0.000000   0.000000`
`22       NaN        NaN    0.000000   0.000000`
`23       NaN        NaN    0.000000   0.000000`

**Comment by BDonnot** [comment] 2019-12-13 16:23
I think what is happening here is that you connect a power line to an empty bus. As you said the power line is "alone" on its bus at one of its end, which is equivalent, from a power system point of view to disconnect it I guess. 

I will check as soon as possible if the extremity bus is properly set up as "active" when you di that. This might suggest it is not the case. 

There are actually 28 entries in this table, the reason is that you can have 2 buses per substations.
This is how the panda power original grid has been modified to allow for bus splitting.

**Comment by BDonnot** [comment] 2019-12-17 14:44
@KishanGitASU @amar-iastate this bug is fixed in version 0.4.1 of grid2op (but probably not on the competition docker unfortunately).
Feel free to check and let me know if there is something not working.

Problem was in the PandaPowerBackend, i didn't set the right bus id when I reconnect only 1 object to it. This is now fixed and tested.

Thanks for raising this error

**Comment by BDonnot** [comment] 2020-01-27 17:59
Error has not reappeared since more than a month, the fix apparently solved this issue.

**Closed by BDonnot** 2020-01-27 17:59 UTC
